# Hexo Configuration - English Version
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Leion's Blog
subtitle: 'Personal Tech Blog'
description: 'Sharing technical insights and life reflections'
keywords: technology,blog,frontend,backend
author: Leion Charrrrls
language: en
timezone: ''

# URL
url: https://leion.ssatop.top
root: /en/
permalink: posts/:abbrlink.html
permalink_defaults:
# 博客链接优化 - 使用slug替代中文标题
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public/en   # 直接生成输出到位，省去后续再次移动
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:
  - "**/*-zh.md"    # 忽略中文文件，只生成英文版本

# Extensions
theme: butterfly

# Algolia搜索配置
algolia:
  applicationID: '5INFST4F2A'
  apiKey: '6d4ddb96ac3fa4b4887f8ce14c27de4b'
  indexName: 'hexo-en'
  chunkSize: 5000
  fields:
    - content:strip:truncate,0,500
    - excerpt:strip
    - gallery
    - permalink
    - photos
    - slug
    - tags
    - title

# 搜索配置
search:
  path: search.xml
  field: all

# abbrlink config
abbrlink:
  alg: crc32      # Algorithm used to calc abbrlink. Support crc16(default) and crc32
  rep: hex        # Representation of abbrlink in URLs. Support dec(default) and hex
  drafts: false   # Whether to generate abbrlink for drafts. (false in default)
  force: false    # Enable force mode. In this mode, the plugin will ignore the cache, and calc the abbrlink for every post even it already had an abbrlink. (false in default)
  writeback: true # Whether to write changes to front-matters back to the actual markdown files. (true in default)

# Feed RSS配置
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

# Sitemap站点地图配置
sitemap:
  path: 
    - sitemap.xml
    - sitemap.txt
  rel: true
  tags: true
  categories: true

# 百度Sitemap配置
baidusitemap:
  path: baidusitemap.xml

# NoFollow外链优化配置
nofollow:
  enable: true
  field: site
  exclude:
    - 'leion.ssatop.top'

# Deployment
deploy:
  type: ''